-- INSERTAR USUARIOS
INSERT INTO user (username, password, nom, prenom, email, date_inscription, imgurl) VALUES
('Abdelaziz', '$2a$11$ADtR0oWyRi/Bd8kP3rvD9.lBlbCK5TOw8tm1oyhB2zv426maNbSge', 'Edwin', 'Dominguez',
 'edwindominguez@hotmail.com', '2019-09-10', 'https://i.imgur.com/T0n0PH9.jpg'),
('demo', '$2a$11$ADtR0oWyRi/Bd8kP3rvD9.lBlbCK5TOw8tm1oyhB2zv426maNbSge', 'demo', 'test', 'demo@demo.com', '2019-09-10', 'https://i.imgur.com/k4k1fOM.png');
-- INSERTAR ROLES
INSERT INTO auth_user_group (username, auth_group) VALUES('Abdelaziz', 'USER');
INSERT INTO auth_user_group (username, auth_group) VALUES('Abdelaziz', 'ADMIN');
INSERT INTO auth_user_group (username, auth_group) VALUES('demo', 'USER');
-- INSERTAR PROFESORES
INSERT INTO tuteur (nom, prenom, email, description, detail, imgurl) VALUES
( 'Esteban', 'Fernandez', 'efernandez@gmail.com', 'Profesor de Java', 'Soy Ingeniero en InformÃ¡tica y me gusta mucho compartir mis conocimientos y experiencia como programador. He trabajado en numerosas empresas de Argentina, Estados Unidos y EspaÃ±a. Cuento con 2 aÃ±os de experiencia dando clases en los siguientes temas: Internet, Java, Microsoft Office, C#, Visual Basic y SQL Server, tanto en empresas y como a alumnos particulares.', 'https://i.imgur.com/hhuQ4yc.jpg'),
( 'Juana', 'Magdalena', 'jmagdalena@hotmail.com', 'Profesora de UX', '15 aÃ±os como profesional en el mundo de la educaciÃ³n privada, impartiendo clases en empresas ( TelefÃ³nica, Securitas Direct, Diario As, Marca, Guardia Civil, Stiga, Alten, etc ) y en diversas escuelas de Barcelona y Madrid ( IDEP, Elisava, Program Acces, RTD, Fomento Nacional del trabajo, Crea ConsultorÃ­a ).', 'https://i.imgur.com/WwVezDt.jpg'),
( 'Pedro', 'Navaja', 'pnavaja@outlook.com', 'Profesor de Python', 'Ing. de Sistemas de la Universidad Nacional Mayor de San Marcos con experiencia en desarrollo de software y dictado de clases de programaciÃ³n a nivel bÃ¡sico, intermedio y avanzado en los lenguajes Python, C/C++, Java, R, Matlab, Octave y JavaScript y bases de datos MySQL y PostgreSQL.', 'https://i.imgur.com/b2kSFna.jpg'),
( 'Maria', 'Mercedes', 'mmercedes@yahoo.com', 'Profesora de algoritmos', 'Estudio Ciencias de la Computacion, y antes estudia Ingenieria Informatica. Me gusta enseÃ±ar en mis ratos libres. Siento que mi metodologia de enseÃ±ar con fundamentos solidos basicos, para poder despues subir el nivel con ejercicios intermedios y dificiles ayuda a mis alumnos a tener esa evolucion y vision para la materia que quieran aprender. Mis clases son amenas y soy muy paciente para enseÃ±ar y comprensible, no importa el nivel que tengan.', 'https://i.imgur.com/swUNc4x.jpg'),
('Alberto', 'Ibarra', 'aibarra@hotmail.com', 'Profesor de HTML','Ingeniero de Sistemas con experiencia en desarrollo de software escritorio y web. Con conocimientos en tecnologÃ­as como Java, Php, Javascript, Html, Css. Brindo clases a domicilio en la ciudad de Huaraz, a estudiantes o cualquier persona que este iniciando el aprendizaje de estas tecnologÃ­as. Se enseÃ±a tambiÃ©n uso de frameworks de Php como Laravel, de Javascript como Vuejs y de Css como Bootstrap4.', 'https://i.imgur.com/rtb0xJF.jpg'),
('Jose', 'Domingo', 'jdomingo@hotmail.com', 'Profesor de Linux', 'Ingeniero en Redes y Comunicaciones, Magister con mas de 7 aÃ±os de experiencia en el Ã¡mbito de la Seguridad InformÃ¡tica, Seguridad de redes, Seguridad Perimetral, AdministraciÃ³n de entornos de virtualizaciÃ³n y AdministraciÃ³n de Sistemas Operativos Linux - Windows. con capacidad de Dictar Linux (bÃ sico, Intermedio, Avanzado) Windows Server(bÃ sico, intermedio avanzado), ccna, seguridad perimetral, entre otros', 'https://i.imgur.com/r6yq088.jpg'),
('Stefany', 'Carranza', 'scarranza@gmail.com', 'Profesora de Javascript', 'Soy desarrolladora web en una empresa y llevo inmerso en el mundo de la programaciÃ³n y la informÃ¡tica desde los 15 aÃ±os. Me encanta programar y todo lo relacionado con Internet y las nuevas tecnologÃ­as, crear cosas y enseÃ±ar a los demÃ¡s. Soy casi completamente autodidacta, por eso voy a ofrecerte muchos de mis conocimientos para que tÃº puedas aprender mÃ¡s fÃ¡cilmente y mÃ¡s rÃ¡pido de lo que yo lo hice y hago cada dÃ­a.', 'https://i.imgur.com/l053VCb.jpg'),
('Ismael', 'Lopez', 'slopez@outlook.com', 'Profesor de Base de Datos', 'Actualmente me dedico como consultor para una compaÃ±Ã­a multinacional EVERIS SAC. En la cual me dedico a analizar y programar dando soluciones a escenarios u problemas de negocio para el cliente de CLARO. Soy apasionado a enseÃ±ar y poder transmitir todo mis conocimientos.', 'https://i.imgur.com/Olu2PuN.jpg');
-- INSERTAR CURSOS
INSERT INTO formation (titre, description, tuteur_id, detail, difficulte, url, imgurl) VALUES
( 'Essential Java', 'Curso de Java para beginners', 1, 'Si lo que buscas es aprender a programar en Java con este curso obtendrÃ¡s conocimientos de programaciÃ³n orientada a objetos a travÃ©s de uso y manejo del lenguaje. Asimismo, con el curso de java desarrollarÃ¡s aplicaciones en consola, formularios y applets, jsp para internet y muchas cosas mÃ¡s .', 'Facil', 'https://www.youtube.com/watch?v=4sZHxFEyEiE&list=PLg9145ptuAihudcXnj8yGBtVWFI6hrrF_', 'https://i.imgur.com/TYsitPM.jpg'),
( 'UX Principles', 'Curso de Experiencia de usuario', 2, 'Sobran muchas razones para explicar por quÃ© debes entrar al mundo del User Experience pero antes de empezar a enumerarlas, Â¿sabes quÃ© es el UX. El UX en espaÃ±ol es traducido como la experiencia del usuario. En tÃ©rminos generales es lo que una persona percibe al interactuar con una plataforma. Se considera un buen UX cuando el diseÃ±o, acomodo de elementos y usabilidad ayudan a que la navegaciÃ³n sea amigable y fÃ¡cil de usar.', 'Facil', 'https://www.youtube.com/watch?v=WAi6ixIfdd4&list=PL0X3cJoTgTdNqlc7tdxCioWU-KDKsUKGC', 'https://i.imgur.com/6wp7WIL.jpg'),
( 'Advanced Python', 'Curso de Python Avanzado',3, 'El Curso Avanzado de Python es una formaciÃ³n 100 % online dedicada a abordar las caracterÃ­sticas mÃ¡s novedosas del lenguaje. Con un carÃ¡cter prÃ¡ctico, permitirÃ¡ dominar las recientes mejoras de la tecnologÃ­a en la realizaciÃ³n de todo tipo de proyectos.', 'Avanzado', 'https://www.youtube.com/watch?v=L_uSbumFspA&list=PLHuhHKl6z1bprks2gYxCj1TWY-7_QRukx', 'https://i.imgur.com/A8lUV2h.jpg'),
( 'Algorithms 101', 'Curso de Algoritmos para beginners',4, 'En la base de cada soluciÃ³n en programaciÃ³n, hay un algoritmo, en este curso vamos a introducirte a la terminologÃ­a, las formas y el diseÃ±o de algoritmos. Este curso forma parte de nuestra especialidad de IntroducciÃ³n a la ProgramaciÃ³n, y te enseÃ±anza a solucionar problemas con algoritmos.', 'Facil', 'https://www.youtube.com/watch?v=YFdXfehe2bo', 'https://i.imgur.com/Xn6TdHy.jpg'),
( 'HTML Basics', 'Curso de HTML para beginners', 5, 'HTML es el lenguaje sobre el que estÃ¡ construida toda la web y su estÃ¡ndar HTML5 la revolucionÃ³ por completo haciendo del navegador el programa mÃ¡s usado en el mundo. Este curso fue dictado en la Facultad de IngenierÃ­a de Sistemas de la Universidad Nacional Mayor de San Marcos en Lima, PerÃº y es ofrecido completamente gratis para que comiences tu carrera en el desarrollo web.', 'Facil', 'https://www.youtube.com/watch?v=rbuYtrNUxg4', 'https://i.imgur.com/gz7yrFb.jpg'),
( 'Advanced HTML', 'Curso de HTML Avanzado', 5, 'Aprende APIs de HTML5 que te permitirÃ¡n crear aplicaciones web con capacidades extendidas, acceso al hardware del equipo del usuario, geolocalizaciÃ³n, storage en el cliente y mucho mÃ¡s. Aprender las APIs que HTML5 introdujo te ayudarÃ¡ a expandir el entendimiento de lo que las pÃ¡ginas pueden hacer.', 'Intermedio', 'https://www.youtube.com/watch?v=QGSxIjjlu3k&list=PLgCfweEKfNwdBW5CBK_XLaD4Rw8sHi2Ur', 'https://i.imgur.com/i9DWWST.jpg'),
( 'Linux Essentials', 'Curso de Linux bÃ¡sico', 6, 'Linux es el sistema operativo con mayor adopciÃ³n para la administraciÃ³n de servidores en Internet. Domina la administraciÃ³n del sistema operativo, archivos, permisos, usuarios y paquetes. Utiliza herramientas para monitorear servicios y procesos. Establece tareas programadas. Configura la seguridad de tu servidor y red para reducir vulnerabilidades.', 'Facil', 'https://www.youtube.com/watch?v=lFjmNiPO0cg&list=PLD2wfKpqmxnnFR7H3TfRpdjEHmTpwyLiS', 'https://i.imgur.com/GVTu9L4.jpg'),
( 'Bash Shell', 'Curso de terminal de Linux', 6, 'Todos los sistemas operativos se pueden programar y expresar en comandos. Por ejemplo en Windows es CMD, en Mac y Linux es la terminal o el â€œShellâ€�. El lenguaje es conocido como â€œBashâ€�. Con Bash-Shell puedes: manipular archivos y carpetas, ejecutar aplicaciones, conectar una Apps, automatizar procesos repetitivos y preparar desde tu computadora personal hasta una nube de servidores.', 'Intermedio', 'https://www.youtube.com/watch?v=Jp-5bPY5Auk', 'https://i.imgur.com/6LzvoX1.jpg'),
( 'JavaScript Essential Training', 'Curso de Javascript BÃ¡sico',7, 'Aprende a fondo JavaScript, el lenguaje de programaciÃ³n mÃ¡s usado en el mundo detrÃ¡s de los ancestrales C y Java, es un lenguaje con el que puedes programar en el Frontend de una pÃ¡gina web, como tambiÃ©n en el Backend, ademÃ¡s tambiÃ©n puedes generar aplicaciones hÃ­bridas para telÃ©fonos y mucho mÃ¡s. El curso te enseÃ±a desde lo bÃ¡sico, hasta EcmaScript 5 y EcmaScript 6, las versiones mÃ¡s nuevas de Javascript.', 'Facil', 'https://www.youtube.com/watch?v=RqQ1d1qEWlE', 'https://i.imgur.com/5epwqY9.jpg'),
( 'Advanced JavaScript', 'Curso de Javascript Avanzado',7, 'Mejora tus habilidades en Javascript. Conoce Typescript y cÃ³mo puedes ocuparlo para mejorar el control de tus variables. Comprende conceptos avanzados que te permitan plantear mejores soluciones en tu cÃ³digo. Conoce las APIs del DOM y descubre cÃ³mo puedes organizar mejor tu cÃ³digo utilizando patrones de diseÃ±o.', 'Intermedio', 'https://www.youtube.com/watch?v=kQ1xYjKFZJ4&list=PLEqCKDlY-B34buE_XNwV8Ri0hoIMP6GhR', 'https://i.imgur.com/vIBF1SA.jpg'),
( 'NodeJS Essential Training', 'Curso de backend con NodeJS',7, 'Crea aplicaciones backend utilizando Node.js, Express y Mongo. Entiende cÃ³mo funciona Javascript en un servidor y escribe aplicaciones con Node.js. Crea una API, manipula errores y valida tus datos con Express. Elabora pruebas para encontrar errores en tu cÃ³digo y finalmente pon tu aplicaciÃ³n en producciÃ³n en un servicio web.', 'Avanzado', 'https://www.youtube.com/watch?v=fLZ3L9MIXAQ&list=PLpOqH6AE0tNjx0SzNvlsP9-JGJ0zmuFnS', 'https://i.imgur.com/Uy5H4Ze.jpg'),
( 'SQL Essential Training', 'Curso de SQL BÃ¡sico',8, 'Conoce el mundo de las bases de datos para entender cÃ³mo trabajan, cÃ³mo se instalan, y las diferencias entre las distintas marcas (SQL Server, MySQL, Oracle, etc.). Aprende lo fundamental para el manejo y manipulaciÃ³n de datos.', 'Facil', 'https://www.youtube.com/watch?v=iOiyJgnN71c&list=PLU8oAlHdN5Bmx-LChV4K3MbHrpZKefNwn', 'https://i.imgur.com/0ol7b83.jpg'),
( 'Advanced SQL', 'Curso de SQL Avanzado',8, 'En este curso aprenderÃ¡s las reglas que se deben considerar durante el proceso de elaboraciÃ³n de modelos de base de datos y de diseÃ±o de una base datos, asÃ­ como, el lenguaje necesario para la creaciÃ³n de sus objetos y manipulaciÃ³n de informaciÃ³n desde un gestor de base de datos.', 'Avanzado', 'https://www.youtube.com/watch?v=XI5JhpgslL8&list=PLszrufyty21qkFGdF70qfJXXxKwg4MdCC', 'https://i.imgur.com/0jCGazt.jpg'),
( 'MongoDB Essential Training', 'Curso de MongoDB',8, 'Domina las bases de MongoDB, el motor de NoSQL que provee alta capacidad de almacenamiento. Optimiza tus procesos gracias a la velocidad de consulta y aprovecha la escalabilidad de este tipo de bases de datos en tus proyectos.', 'Intermedio', 'https://www.youtube.com/watch?v=lWMemPN9t6Q', 'https://i.imgur.com/qm8cxhp.jpg');
-- INSERTAR MATRICULAS
INSERT INTO progression (user_id, formation_id, dateins) VALUES ( 1, 3, '2019-10-10' ),
                                                        ( 2, 1, '2019-11-01'),
                                                        ( 2, 4, '2019-11-02' );